name: Coordinator

on:
  push:
    branches: [main]
  pull_request:

env:
  NODE_OPTIONS: "--max-old-space-size=8192"
  TTL: 60000
  LIMIT: 10
  COORDINATOR_PUBLIC_KEY_PATH: "./public.key"
  COORDINATOR_PRIVATE_KEY_PATH: "./private.key"
  COORDINATOR_MACI_PRIVATE_KEY: "macisk.5e203463e80f38f11fecbfeca93cbd78ec40b7d82ccf1ba6068fbc23b99f57b1"
  COORDINATOR_TALLY_ZKEY_NAME: "VoteTally_10-1-2_test"
  COORDINATOR_MESSAGE_PROCESS_ZKEY_NAME: "MessageProcessor_10-20-2_test"
  COORDINATOR_POLL_JOINING_ZKEY_NAME: "PollJoining_10_test"
  COORDINATOR_POLL_JOINED_ZKEY_NAME: "PollJoined_10_test"
  COORDINATOR_RAPIDSNARK_EXE: ""
  COORDINATOR_ZKEY_PATH: "../../zkeys"
  COORDINATOR_RPC_URL: "http://localhost:8545"
  SUBGRAPH_NAME: "maci-coordinator-subgraph"
  SUBGRAPH_PROVIDER_URL: "https://api.studio.thegraph.com/deploy/"
  SUBGRAPH_DEPLOY_KEY: "subgraph-deploy-key"
  SUBGRAPH_FOLDER: "./node_modules/@maci-protocol/subgraph"
  ZERODEV_BUNDLER_RPC_OP_SEPOLIA: "https://rpc.zerodev.app/api/v3"
  PRIVATE_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: "pnpm"

      - name: Get changed files
        id: get-changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "csv"

      - name: Check for changes in 'circuit' folder
        id: check_changes
        run: |
          CHANGED_FILES=${{ steps.get-changed-files.outputs.all }}
          if echo "$CHANGED_FILES" | grep -q "\.circom"; then
            echo "CHANGED=true" >> $GITHUB_ENV
            echo "Circuits have changes."
          else
            echo "CHANGED=false" >> $GITHUB_ENV
            echo "No changes on circuits."
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            build-essential \
            libgmp-dev \
            libsodium-dev \
            nasm \
            nlohmann-json3-dev

      - name: Install
        run: |
          pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: |
          pnpm run build

      - name: Download rapidsnark (1c137)
        run: |
          mkdir -p ~/rapidsnark/build
          wget -qO ~/rapidsnark/build/prover https://maci-devops-zkeys.s3.ap-northeast-2.amazonaws.com/rapidsnark-linux-amd64-1c137
          chmod +x ~/rapidsnark/build/prover

      - name: Download circom Binary v2.1.6
        run: |
          wget -qO ${{ github.workspace }}/circom https://github.com/iden3/circom/releases/download/v2.1.6/circom-linux-amd64
          chmod +x ${{ github.workspace }}/circom
          sudo mv ${{ github.workspace }}/circom /bin/circom

      - name: Calculate circuits hash
        id: hash_circuits
        run: |
          CIRCUIT_HASH=$(find packages/circuits -type f -name '*.circom' -exec sha1sum {} \; | sort | sha1sum | cut -d ' ' -f1)
          echo "CIRCUIT_HASH=$CIRCUIT_HASH" >> $GITHUB_ENV
          echo "CIRCUIT_HASH=$CIRCUIT_HASH" >> $GITHUB_OUTPUT

      - name: Cache zkeys
        id: cache_zkeys
        uses: actions/cache@v4
        with:
          path: zkeys
          key: zkeys-${{ steps.hash_circuits.outputs.CIRCUIT_HASH }}
          restore-keys: |
            zkeys-

      - name: Compile Circuits And Generate zkeys
        if: ${{ env.CHANGED == 'true' && steps.cache_zkeys.outputs.cache-hit != 'true' }}
        run: |
          pnpm build:circuits-c -- --outPath ../../apps/coordinator/zkeys
          pnpm setup:zkeys -- --outPath ../../apps/coordinator/zkeys

      - name: Download zkeys
        if: ${{ env.CHANGED == 'false' }}
        run: |
          pnpm download-zkeys:test

      - name: Generate RSA Keypair
        working-directory: apps/coordinator
        run: |
          pnpm run generate-keypair

      - name: Run hardhat fork
        working-directory: apps/coordinator
        run: |
          pnpm run hardhat &
          sleep 5

      - name: Run tests
        working-directory: apps/coordinator
        run: |
          pnpm run test

      - name: Stop Hardhat
        if: always()
        run: kill $(lsof -t -i:8545)
