name: Crypto

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install
        run: |
          pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: |
          pnpm run build

      - name: Test
        run: pnpm run test
        working-directory: packages/crypto
