name: Nightly Ceremony

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  test-with-ceremony-keys:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
        with:
          ref: main

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            build-essential \
            libgmp-dev \
            libsodium-dev \
            nasm \
            nlohmann-json3-dev

      - name: Install
        run: |
          pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: |
          pnpm run build

      - name: Download rapidsnark (1c137)
        run: |
          mkdir -p ~/rapidsnark/build
          wget -qO ~/rapidsnark/build/prover https://maci-devops-zkeys.s3.ap-northeast-2.amazonaws.com/rapidsnark-linux-amd64-1c137
          chmod +x ~/rapidsnark/build/prover

      - name: Download circom Binary v2.1.6
        run: |
          wget -qO /home/runner/work/circom https://github.com/iden3/circom/releases/download/v2.1.6/circom-linux-amd64
          chmod +x /home/runner/work/circom
          sudo mv /home/runner/work/circom /bin/circom

      - name: Run e2e tests
        working-directory: packages/circuits
        run: pnpm test:ceremonyParams

      - name: Notify on failure
        if: ${{ always() && (failure() || cancelled()) }}
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          -d '{"text": ":x: GitHub Actions job *${{ github.workflow }}* failed in *${{ github.repository }}* on branch *${{ github.ref }}*. [View run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"}' \
          ${{ secrets.WEBHOOK_URL }}
